version: '3'

services:
  ignite:
    image: apacheignite/ignite
    volumes:
      - "../src/main/resources/ignite-config.xml:/ignite-config.xml"
    environment:
      - CONFIG_URI=file:/ignite-config.xml
    deploy:
      mode: replicated
      replicas: 3
